[package]
name = "vcs2600"
version = "0.1.0"
authors = ["Ludovic PeÌnet <ludovic.penet@dataiku.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.2"
termimage = "0.5.0"
image = "0.22.3"
